[theme]
# Mode Light sebagai default
base = "light"

# Primary color (warna aksen utama)
primaryColor = "#2563eb"

# Warna font utama (Slate 900)
textColor = "#0f172a"

# Background utama (Slate 50)
backgroundColor = "#f8fafc"

# Background komponen / sidebar (Pure White)
secondaryBackgroundColor = "#ffffff"

